CREATE TABLESPACE BOOKSTOREBIG 
DATAFILE 'C:\ORACLE11G\BOOKSTOREBIG.DBF' SIZE 100000K;

CREATE SEQUENCE secuencia
START WITH 1 INCREMENT BY 1;


CREATE TABLE L_CLIENTES
(
    IdCliente INTEGER NOT NULL,
    Nombre VARCHAR2(20) NOT NULL,
    Apellidos VARCHAR2(40) NOT NULL,
    eMail VARCHAR2(50) NOT NULL,
    Nick VARCHAR2(20) NOT NULL,
    Clave VARCHAR2(20) NOT NULL,
    FHAlta TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    Activo SMALLINT DEFAULT 1 NOT NULL,
    
    CONSTRAINT PK_CLIENTES PRIMARY KEY (IdCliente),
    CONSTRAINT AK_CLIENTES UNIQUE (Nick),
    CONSTRAINT UQ_EMAIL UNIQUE (eMail),
    CONSTRAINT CK_NICK CHECK (Length(Nick) BETWEEN 4 AND 20),
    CONSTRAINT CK_CLAVE CHECK (Length(Clave) BETWEEN 4 AND 20),
    CONSTRAINT CK_ACTIVO CHECK (Activo IN (0 ,1))
)
TABLESPACE BOOKSTOREBIG;

CREATE TABLE L_INFO_NOVEDADES
(
    IdCliente     INTEGER NOT NULL,
    IdGenero      INTEGER NOT NULL,
    TipoAviso     VARCHAR2(12) NOT NULL,
    
    CONSTRAINT PK_INFO_NOVEDADES PRIMARY KEY (IdCliente, IdGenero),
    CONSTRAINT FK_INFO_CLIENTE
      FOREIGN KEY (IdCliente)
      REFERENCES L_CLIENTES(IdCliente)
      ON DELETE CASCADE,
    CONSTRAINT FK_INFO_GENERO
      FOREIGN KEY (IdGenero)
      REFERENCES L_GENEROS (IdGenero)
      ON DELETE CASCADE,
    CONSTRAINT CK_TIPOAVISO CHECK (TipoAviso IN ('email', 'notificacion'))
)
TABLESPACE BOOKSTOREBIG;


CREATE TABLE L_AVISOS
(
    IdAviso     INTEGER NOT NULL,
    NickCliente VARCHAR2(20) NOT NULL,
    Texto       VARCHAR2(500) NOT NULL,
    Visto       SMALLINT DEFAULT 0 NOT NULL,
    
    CONSTRAINT PK_AVISOS PRIMARY KEY (IdAviso),
    CONSTRAINT FK_AVISO_CLIENTE 
      FOREIGN KEY (NickCliente)
      REFERENCES L_CLIENTES (Nick)
      ON DELETE CASCADE,
    CONSTRAINT CK_AVISO_VISTO CHECK (Visto IN (0, 1))
)
TABLESPACE BOOKSTOREBIG;


CREATE TABLE L_COMPRAS
(
    IdCompra INTEGER NOT NULL,
    IdLibro INTEGER NOT NULL,
    NumEjemplares INTEGER NOT NULL,
    PrecioLote NUMBER(9, 2) NOT NULL,
    FechaCompra DATE NOT NULL,
    
    CONSTRAINT PK_COMPRAS PRIMARY KEY (IdCompra),
    CONSTRAINT FK_COMPRA_LIBRO 
      FOREIGN KEY (IdLibro)
      REFERENCES L_LIBROS (IdLibro)
      ON DELETE CASCADE,
    CONSTRAINT CK_COMPRA_NUMEJEMPLARES CHECK (NumEjemplares > 0),
    CONSTRAINT CK_COMPRA_PRECIOLOTE CHECK (PrecioLote > 0)
)
TABLESPACE BOOKSTOREBIG;

CREATE TABLE L_ALMACEN
(
    IdLibro INTEGER NOT NULL,
    Stock INTEGER NOT NULL,
    PrecioCompraUnidad NUMBER(5, 2) NOT NULL,
    PrecioVentaUnidad NUMBER(5, 2) NOT NULL,
    UltimaRevision TIMESTAMP DEFAULT SysTimeStamp NOT NULL,
    
    CONSTRAINT PK_ALMACEN PRIMARY KEY (IdLibro),
    CONSTRAINT FK_ALMACEN_LIBRO 
      FOREIGN KEY (IdLibro)
      REFERENCES L_LIBROS (IdLibro)
      ON DELETE CASCADE,
    CONSTRAINT CK_PRECIOCOMPRAUNIDAD CHECK (PrecioCompraUnidad > 0),
    CONSTRAINT CK_PRECIOVENTAUNIDAD CHECK (PrecioVentaUnidad > 0),
    CONSTRAINT CK_GANANCIA CHECK (PrecioVentaUnidad > PrecioCompraUnidad)
)
TABLESPACE BOOKSTOREBIG;



CREATE TABLE L_VENTAS
(
    IdVenta INTEGER NOT NULL,
    IdLibro INTEGER NOT NULL,
    IdCliente INTEGER NOT NULL,
    Precio NUMBER(5, 2) NOT NULL,
    FHVenta TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_VENTAS PRIMARY KEY (IdVenta),
    CONSTRAINT FK_VLIBRO 
      FOREIGN KEY (IdLibro)
      REFERENCES L_LIBROS (IdLibro)
      ON DELETE CASCADE,
    CONSTRAINT FK_VCLIENTE
      FOREIGN KEY (IdCliente)
      REFERENCES L_CLIENTES (IdCliente)
      ON DELETE CASCADE
)
TABLESPACE BOOKSTOREBIG;

CREATE TABLE L_PAISES
(
    IdPais INTEGER NOT NULL,
    Denom VARCHAR2(40) NOT NULL,
    
    CONSTRAINT PK_PAISES PRIMARY KEY (IdPais),
    CONSTRAINT UQ_NOMBRE UNIQUE (Denom)
)
TABLESPACE BOOKSTOREBIG;


CREATE TABLE L_AUTORES
(

    IdAutor   INTEGER NOT NULL,
    Nombre    VARCHAR2(20) NULL,
    Apellidos VARCHAR2(40) NULL,
    Seudonimo VARCHAR2(40) NULL,
    KnownBy   VARCHAR2(11) NOT NULL, 
    FechaNac  INTEGER NULL,
    FechaDef  INTEGER NULL,
    PaisNac   INTEGER NOT NULL,
    Biografia VARCHAR2(800) NULL,
    
    CONSTRAINT PK_AUTORES PRIMARY KEY (IdAutor),
    CONSTRAINT UQ_AUTORES UNIQUE (Nombre, Apellidos),    
    CONSTRAINT UQ_SEUDONIMO UNIQUE (Seudonimo),
    
    CONSTRAINT CK_QUIEN
      CHECK ((Nombre IS NOT NULL) OR (Seudonimo IS NOT NULL)),
      
    CONSTRAINT CK_KNOWNBY
      CHECK (KnownBy IN ('Nombre real', 'Seudónimo')),
      
    CONSTRAINT CK_FECHAS
      CHECK ((FechaDef > FechaNac) OR (FechaDef IS NULL) OR (FechaNac IS NULL)),
    
    CONSTRAINT FK_A_PAISES 
      FOREIGN KEY (PaisNac) REFERENCES L_PAISES (IdPais)
      
)
TABLESPACE BOOKSTOREBIG;



CREATE TABLE L_GENEROS
(
    IdGenero  INTEGER NOT NULL,
    Denom     VARCHAR(40) NOT NULL,
    
    CONSTRAINT PK_GENEROS PRIMARY KEY (IdGenero),
    CONSTRAINT UQ_GENEROS UNIQUE (Denom)
    
)
TABLESPACE BOOKSTOREBIG;


CREATE TABLE L_EDITORIALES
(
    IdEditorial  INTEGER NOT NULL,
    Denom       VARCHAR(40) NOT NULL,
    
    CONSTRAINT PK_EDITORIALES PRIMARY KEY (IdEditorial),
    CONSTRAINT UQ_EDITORIALES UNIQUE (Denom)   
)
TABLESPACE BOOKSTOREBIG;


CREATE TABLE L_IDIOMAS
(
    IdIdioma    INTEGER NOT NULL,
    Denom       VARCHAR(20) NOT NULL,
    
    CONSTRAINT PK_IDIOMAS PRIMARY KEY (IdIdioma),
    CONSTRAINT UQ_IDIOMAS UNIQUE (Denom)
)
TABLESPACE BOOKSTOREBIG;


CREATE TABLE L_LIBROS
(
    IdLibro   INTEGER NOT NULL,
    ISBN      VARCHAR2(30) NOT NULL,
    Titulo    VARCHAR2(70) NOT NULL,
    Autor     INTEGER NOT NULL,
    Genero    INTEGER NOT NULL,
    Editorial INTEGER NOT NULL,
    FechaPublic INTEGER NOT NULL,    
    Edicion   VARCHAR(20) NOT NULL,
    Idioma    INTEGER NOT NULL,
    Sinopsis  VARCHAR2(800) NOT NULL,
    NumPaginas INTEGER NOT NULL,
    FHInsercion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    Activo INTEGER DEFAULT 1 NOT NULL,
    
    CONSTRAINT PK_LIBROS PRIMARY KEY (IdLibro),    
    CONSTRAINT AK_LIBROS UNIQUE (ISBN),
    
    CONSTRAINT FK_L_AUTOR FOREIGN KEY (Autor)
      REFERENCES L_AUTORES (IdAutor),
    CONSTRAINT FK_L_GENERO
      FOREIGN KEY (Genero)
      REFERENCES L_GENEROS (IdGenero),
    CONSTRAINT FK_L_EDITORIAL 
      FOREIGN KEY (Editorial)
      REFERENCES L_EDITORIALES (IdEditorial),
    CONSTRAINT FK_L_IDIOMA
      FOREIGN KEY (Idioma)
      REFERENCES L_IDIOMAS (IdIdioma),
      
    CONSTRAINT CK_FECHAPUBLIC
      CHECK (FECHAPUBLIC BETWEEN 1500 AND EXTRACT(YEAR FROM FHInsercion)),
      
    CONSTRAINT CK_EDICION 
      CHECK (EDICION IN ('Primera', 'Segunda', 'Tercera', 'Cuarta', 'Quinta', 'Sexta',
              'Séptima', 'Octava', 'Novena', 'Décima')),
              
    CONSTRAINT CK_NUMPAGINAS
      CHECK (NumPaginas > 2),
      
    CONSTRAINT CK_LIBRO_ACTIVO CHECK (Activo IN (0,1))      
      
)
TABLESPACE BOOKSTOREBIG;















  

